Холин Никита Андреевич

Задание 1:  Генерация сетки координат

In [9]:
import numpy as np

x = np.arange(-5,6)
y = np.arange(-5,6)

# 2. Генерируем сетку координат с помощью np.meshgrid
X, Y = np.meshgrid(x, y)

# 3. Вычисляем значения функции z = x^2 + y^2 на сетке
Z = X**2 + Y**2

# 4. Выводим массивы x, y и z
print("Массив x:")
print(X)
print("\nМассив y:")
print(Y)
print("\nМассив z = x^2 + y^2:")
print(Z)

Массив x:
[[-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]
 [-5 -4 -3 -2 -1  0  1  2  3  4  5]]

Массив y:
[[-5 -5 -5 -5 -5 -5 -5 -5 -5 -5 -5]
 [-4 -4 -4 -4 -4 -4 -4 -4 -4 -4 -4]
 [-3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3]
 [-2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 0  0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1  1]
 [ 2  2  2  2  2  2  2  2  2  2  2]
 [ 3  3  3  3  3  3  3  3  3  3  3]
 [ 4  4  4  4  4  4  4  4  4  4  4]
 [ 5  5  5  5  5  5  5  5  5  5  5]]

Массив z = x^2 + y^2:
[[50 41 34 29 26 25 26 29 34 41 50]
 [41 32 25 20 17 16 17 20 25 32 41]
 [34 25 18 13 10  9 10 13 18 25 34]
 [29 20 13  8  5  4  5  8 13 20 29]
 [26 17 10  5  2  

Задание 2: Создание двумерного массива

1. python -m venv study-env (создание виртуального окружения)
2. source study-env/bin/activate (активация)
3. pip install numpy (установка requests)
4. pip freeze > requirements.txt (сохранение зависимостейв файл)

    получился файл в котором указаны зависимости а также требуемый модуль

        numpy==2.1.2

In [13]:
import numpy as np

def create_3x3_array():
    """
    Создает одномерный массив от 1 до 9, преобразует его в двумерный массив 3x3 и выводит на экран.
    """
    try:
        # Создание одномерного массива от 1 до 9
        array_1d = np.arange(1, 10)
        
        # Изменение формы массива на 3x3
        array_2d = array_1d.reshape(3, 3)
        
        # Вывод двумерного массива на экран
        print("Полученный массив 3x3:")
        print(array_2d)
    
    except Exception as e:
        # Обработка исключений на случай ошибок при изменении формы массива
        print(f"Произошла ошибка при изменении формы массива: {e}")

create_3x3_array()


Полученный массив 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


6. deactivate (деактивация виртуального окружения)

Задание 3: Изменение формы массива

1. python -m venv study2-env (создание виртуального окружения)
2. source study2-env/bin/activate (активация)
3. pip install numpy (установка requests)
4. pip freeze > requirements.txt (сохранение зависимостейв файл)

    получился файл в котором указаны зависимости а также требуемый модуль

        numpy==2.1.2

In [16]:
import numpy as np

def create_array():
    """
    Создание одномерного массива из 12 случайных чисел.
    Возвращает одномерный массив.
    """
    try:
        # Создание одномерного массива из 12 случайных чисел
        arr = np.random.rand(12)  # Массив случайных чисел от 0 до 1
        print("Исходный одномерный массив:")
        print(arr)
        return arr
    except Exception as e:
        # Обработка ошибок при создании массива
        print(f"Произошла ошибка при создании массива: {e}")
        return None

def reshape_array(arr):
    """
    Изменяет форму массива на 4x3.
    Возвращает измененный массив.
    """
    try:
        # Изменение формы массива на 4x3
        arr_reshaped = arr.reshape(4, 3)
        print("\nИзмененный массив 4x3:")
        print(arr_reshaped)
        return arr_reshaped
    except Exception as e:
        # Обработка ошибок при изменении формы массива
        print(f"Произошла ошибка при изменении формы массива: {e}")
        return None

arr = create_array()
    
# Если массив успешно создан, изменяем его форму
if arr is not None:
    reshape_array(arr)


Исходный одномерный массив:
[0.14386085 0.88429294 0.75310137 0.9408033  0.49871032 0.3073818
 0.00400637 0.92648708 0.36092682 0.99443541 0.19319572 0.27996324]

Измененный массив 4x3:
[[0.14386085 0.88429294 0.75310137]
 [0.9408033  0.49871032 0.3073818 ]
 [0.00400637 0.92648708 0.36092682]
 [0.99443541 0.19319572 0.27996324]]


6. deactivate (деактивация виртуального окружения)

Задание 4: Индексация и срезы

1. python -m venv study3-env (создание виртуального окружения)
2. source study3-env/bin/activate (активация)
3. pip install numpy (установка requests)
4. pip freeze > requirements.txt (сохранение зависимостейв файл)

    получился файл в котором указаны зависимости а также требуемый модуль

        numpy==2.1.2

In [20]:
import numpy as np

arr = np.arange(10,20)

# Выведет элементы с 3-го по 7-й (включительно). индексация начинается с 0 у массивов, соотвественно 3 элемент соответствует 2 индексу, 7 элементу - 6 индексу, но чтобы его включить нужно указать на индекс выше
print(arr[2:7])

# Заменит элементы с 5-го по 8-й на 0.
arr[4:9] = 0

print(arr)

[12 13 14 15 16]
[10 11 12 13  0  0  0  0  0 19]


6. deactivate (деактивация виртуального окружения)

Задание 5: Математические операции с массивами

1. python -m venv study4-env (создание виртуального окружения)
2. source study4-env/bin/activate (активация)
3. pip install numpy (установка requests)
4. pip freeze > requirements.txt (сохранение зависимостейв файл)

    получился файл в котором указаны зависимости а также требуемый модуль

        numpy==2.1.2

In [34]:
import numpy as np

def perform_operations(a, b):
    """
    Функция для выполнения арифметических операций на массивах.
    :param a: первый массив.
    :param b: второй массив.
    :return: результаты операций.
    """
    try:
        # Сумма массивов
        sum_arr = np.add(a, b)
        # Разность массивов
        diff_arr = np.subtract(a, b)
        # Произведение массивов
        prod_arr = np.multiply(a, b)
        # Частное массивов (с проверкой на деление на ноль)
        with np.errstate(divide='ignore', invalid='ignore'):
            # Для деления массивов на 0 мы используем np.errstate, чтобы подавить предупреждения и ошибки деления на ноль.
            # Все значения NaN (которые могут появиться при делении на 0) заменяются на бесконечность (inf)
            div_arr = np.divide(a, b)
            div_arr[np.isnan(div_arr)] = float('inf')

        return sum_arr, diff_arr, prod_arr, div_arr
    except Exception as e:
        print(f"Произошла ошибка при выполнении операций: {e}")
        return None, None, None, None


def print_results(sum_arr, diff_arr, prod_arr, div_arr):
    """
    Функция для вывода результатов операций.
    :param sum_arr: результат сложения.
    :param diff_arr: результат вычитания.
    :param prod_arr: результат умножения.
    :param div_arr: результат деления.
    """
    print("Результаты арифметических операций между массивами a и b:\n")
    
    print("Сумма массивов (a + b):")
    print(sum_arr)
    
    print("\nРазность массивов (a - b):")
    print(diff_arr)
    
    print("\nПроизведение массивов (a * b):")
    print(prod_arr)
    
    print("\nЧастное массивов (a / b):")
    print(div_arr)


# Создаем два массива a и b
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

# Выполняем операции
sum_arr, diff_arr, prod_arr, div_arr = perform_operations(a, b)

# Выводим результаты
print_results(sum_arr, diff_arr, prod_arr, div_arr)



Результаты арифметических операций между массивами a и b:

Сумма массивов (a + b):
[6 6 6 6 6]

Разность массивов (a - b):
[-4 -2  0  2  4]

Произведение массивов (a * b):
[5 8 9 8 5]

Частное массивов (a / b):
[0.2 0.5 1.  2.  5. ]


6. deactivate (деактивация виртуального окружения)

Задание 6: Решение системы линейных уравнений

1. python -m venv study5-env (создание виртуального окружения)
2. source study5-env/bin/activate (активация)
3. pip install numpy (установка requests)
4. pip freeze > requirements.txt (сохранение зависимостей в файл)

    получился файл в котором указаны зависимости а также требуемый модуль

        numpy==2.1.2

In [35]:
import numpy as np

def solve_system():
    """
    Решение системы линейных уравнений с использованием NumPy.
    Уравнения:
    2x + y = 5
    x - y = 1
    """
    # Коэффициенты уравнений
    A = np.array([[2, 1], [1, -1]])  # Матрица коэффициентов
    b = np.array([5, 1])  # Вектор правых частей

    try:
        # Используем np.linalg.solve для решения системы
        solution = np.linalg.solve(A, b)
        
        # Выводим решение
        print(f"Решение системы: x = {solution[0]}, y = {solution[1]}")
    except np.linalg.LinAlgError as e:
        # Обработка ошибок при решении (например, если матрица вырождена)
        print(f"Ошибка при решении системы: {e}")

# Вызов функции для решения системы
solve_system()


Решение системы: x = 2.0, y = 1.0


6. deactivate (деактивация виртуального окружения)

Задание 7: Вычисление собственных значений и векторов

1. python -m venv study6-env (создание виртуального окружения)
2. source study6-env/bin/activate (активация)
3. pip install numpy (установка requests)
4. pip freeze > requirements.txt (сохранение зависимостей в файл)

    получился файл в котором указаны зависимости а также требуемый модуль

        numpy==2.1.2

In [36]:
A = np.array([[2,0], [0,3]])

# Вычисления собственных значений и собственных векторов матрицы
eigenvalues, eigenvectors = np.linalg.eig(A)

# Выводим результаты
print("Собственные значения:")
print(eigenvalues)

print("\nСобственные векторы:")
print(eigenvectors)

Собственные значения:
[2. 3.]

Собственные векторы:
[[1. 0.]
 [0. 1.]]


6. deactivate (деактивация виртуального окружения)

Задание 8: Соединение массивов

1. python -m venv study7-env (создание виртуального окружения)
2. source study7-env/bin/activate (активация)
3. pip install numpy (установка requests)
4. pip freeze > requirements.txt (сохранение зависимостей в файл)

    получился файл в котором указаны зависимости а также требуемый модуль

        numpy==2.1.2

In [13]:
import numpy as np
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')


def stack_arrays():
    """
    Функция для создания и соединения массивов:
    1. Горизонтально с помощью hstack.
    2. Вертикально с помощью vstack.
    """

    # Создание массивов
    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])

    try:
        logging.info("Производится горизонтальное соединение...")
        # Горизонтальное соединение
        horizontal_stack = np.hstack((a, b))
        print("Горизонтальное соединение (hstack):")
        print(horizontal_stack)

        logging.info("Производится вертикальное соединение...")
        # Вертикальное соединение
        vertical_stack = np.vstack((a, b))
        print("\nВертикальное соединение (vstack):")
        print(vertical_stack)

    except Exception as e:
        print(f"Произошла ошибка при соединении массивов: {e}")



stack_arrays()


2024-11-28 09:33:41,037 - INFO - Производится горизонтальное соединение...
2024-11-28 09:33:41,038 - INFO - Производится вертикальное соединение...


Горизонтальное соединение (hstack):
[1 2 3 4 5 6]

Вертикальное соединение (vstack):
[[1 2 3]
 [4 5 6]]


6. deactivate (деактивация виртуального окружения)

Задание 9: Замена максимального элемента массива

1. python -m venv study8-env (создание виртуального окружения)
2. source study8-env/bin/activate (активация)
3. pip install numpy (установка requests)
4. pip freeze > requirements.txt (сохранение зависимостей в файл)

    получился файл в котором указаны зависимости а также требуемый модуль

        numpy==2.1.2

In [16]:
import numpy as np

def replace_max_with_zero():
    """
    Функция для создания массива, нахождения максимального элемента,
    замены его на 0 и вывода результатов.
    """
    try:
        # Шаг 1: Создаем массив из 10 случайных целых чисел от 1 до 100
        arr = np.random.randint(1, 101, size=10)
        print("Исходный массив:")
        print(arr)

        # Шаг 2: Находим индекс максимального элемента
        max_index = np.argmax(arr)  # Индекс максимального элемента

        # Шаг 3: Заменяем максимальный элемент на 0
        arr[max_index] = 0

        # Шаг 4: Вывод измененного массива
        print("\nИзмененный массив:")
        print(arr)

    except Exception as e:
        print(f"Произошла ошибка: {e}")



replace_max_with_zero()


Исходный массив:
[50 10 70 82 17 37 91  7 25  2]

Измененный массив:
[50 10 70 82 17 37  0  7 25  2]


6. deactivate (деактивация виртуального окружения)

Задание 10: Нахождение среднего значения по столбцам

1. python -m venv study9-env (создание виртуального окружения)
2. source study9-env/bin/activate (активация)
3. pip install numpy (установка requests)
4. pip freeze > requirements.txt (сохранение зависимостей в файл)

    получился файл в котором указаны зависимости а также требуемый модуль

        numpy==2.1.2

In [19]:
import numpy as np

def calculate_column_means():
    """
    Создание матрицы 4x5, нахождение среднего значения по столбцам
    и вывод результатов.
    """
    try:
        # Шаг 1: Создаем матрицу 4x5 со случайными целыми числами от 0 до 10
        matrix = np.random.randint(0, 11, size=(4, 5))
        print("Матрица 4x5:")
        print(matrix)

        # Шаг 2: Вычисляем среднее значение по каждому столбцу
        column_means = np.mean(matrix, axis=0)

        # Шаг 3: Выводим средние значения
        print("\nСредние значения по столбцам:")
        print(column_means)

    except Exception as e:
        print(f"Произошла ошибка: {e}")



calculate_column_means()


Матрица 4x5:
[[8 9 7 8 2]
 [5 5 1 1 3]
 [9 4 1 6 5]
 [4 9 0 6 4]]

Средние значения по столбцам:
[6.5  6.75 2.25 5.25 3.5 ]


6. deactivate (деактивация виртуального окружения)